name: Build and test

on:
  push:
    branches:
      - stage
      - master
  pull_request:
    branches:
      - stage
      - master

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Enable Corepack
        run: corepack enable
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
        if: (github.event_name == 'push' && github.ref != 'refs/heads/master') || (github.event_name == 'pull_request' && github.base_ref != 'master')
